# Global context
[build]
	# Base directory
	base = "$DIRECTORY"
	# Build command
	command = "npx slidev build"
	# Build directory
	publish = "dist/"

# Enforce Node version
[build.environment]
	NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
	force = false
