[build]
base = ""
command = "cd $DIRECTORY && npx slidev build && mv dist ../dist && rm ../dist/_redirects"
publish = "dist/"
ignore = "git diff --quiet HEAD^ HEAD ./package.json ./netlify.toml \"./${DIRECTORY}/\""

[build.environment]
NODE_VERSION = "22"

[[redirects]]
from = "/assets/fonts/*"
to = "https://lihbr.com/assets/fonts/:splat"
status = 200
force = false

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
